### ISSUE TITLE
很好用的脚本,就是只能在Debian 上用... 

### ISSUE THREAD

**Issue by wcg928** [Readour/AR-B-P-B#4]
Ubuntu  和 CentOS 安装测试都没成功..  希望大侠继续更新....谢谢了!

**Comment by zyh001** [comment]
@wcg928 你好，脚本是支持Ubuntu和CentOS的，麻烦发一下具体的错误信息，谢谢

**Comment by KiritoMiao** [comment]
@wcg928 请提交log

**Comment by wcg928** [comment]
我是新手,,当时用了Ubuntu和CentOS 的系统装,都有问题..后来改用Debian才成功....没有保存LOG和错误信息....也可能我装方法不对

**Comment by zyh001** [comment]
@wcg928 下次出问题麻烦附上错误信息，便于改进，谢谢
