### ISSUE TITLE
用的这个脚本,前2天VPS的IP被GFW屏蔽了...

### ISSUE THREAD

**Issue by wcg928** [Readour/AR-B-P-B#8]
目前国内PING不同..国外的IP可以..

**Comment by zyh001** [comment]
@wcg928 使用脚本和VPS被墙没有直接关系，墙是自主嗅探的，脚本不会上传你的信息

**Comment by wcg928** [comment]
恩,这个封是针对SSR的...定像爆破啊

2018-02-06 14:19 GMT+08:00 stack zhao <notifications@github.com>:

**Comment by zyh001** [comment]
@wcg928 那就和脚本关系不大，并不是定向爆破，只是批量扫段，我依然力挺SSR，所以脚本我一直在更新

**Comment by kj415j45** [comment]
会不会是你留了SS兼容的梯子，导致扫描SS的时候被嗅探 🤔
